### ISSUE TITLE
handlers\rest\base.go:30:29: c.Request.Header.Values undefined

### ISSUE THREAD

**Issue by bergkamp2008999** [lyonsdpy/phoenix#2]
# github.com/phoenix/phoenix/handlers/rest
handlers\rest\base.go:30:29: c.Request.Header.Values undefined (type http.Header has no field or method Values)
handlers\rest\base.go:43:25: c.Request.Header.Values undefined (type http.Header has no field or method Values)

**Comment by lyonsdpy** [comment]
go version >=1.14
versions before 1.14 don't have func `Values` in net/http/Request/Header
